### ISSUE TITLE
fbyte.facade licence

### ISSUE THREAD

**Issue by lekowalski** [Fresh-Byte/facade#1]
В Facade не могу ничего изменять/добавлять. Всплывает окно "Нарушены условия лицензии 'fbyte.facade'

**Comment by lekowalski** [comment]
В Facade не могу ничего изменять/добавлять. Всплывает окно "Нарушены условия лицензии 'fbyte.facade'

**Comment by Rombs** [comment]
Добрый день!
Поправил лицензию. Должно заработать
